---
config:
  theme: 'default'

title: Unicast
---

flowchart TD
    Switch((Switch))

    subgraph Broadcast_Clients["Clients"]
        Client1((Client 1))
        Client2((Client 2))
        Client3((Client 3))
        Client4((Client 4))
    end

   
    Switch --> Client2
 




